### ISSUE TITLE
$'\r' error

### ISSUE THREAD

**Issue by technologistzero** [elmsln/HAXcms#113]
open git bash in project folder and run `ddev start` to get around the error.

**Comment by btopro** [comment]
To get around what error? Could you provide a bit more detail of environment or how you got an error? Was this windows?

**Comment by btopro** [comment]
if this is a documentation issue please feel free to issue a PR against the docs section or the https://github.com/elmsln/haxtheweb.org doc section

**Comment by btopro** [comment]
closing, please reopen if this still exists
