### ISSUE TITLE
[site-conditional] conditional site logic / rendering

### ISSUE THREAD

**Issue by btopro** [elmsln/HAXcms#124]
Wrap and simplify the writing of dom-if tags to so something like this:
```
<template is="dom-if" if="[[matches(activeItem.title, "blogs")]]"> do something </template>
```

**Comment by michael-collins** [comment]
The ability to create if statements that evaluate multiple criteria at once would be cool, like:

```
if submission.image != null AND submission.role == student AND submission.published == true {

<div> something here </div>

else {
nadda
}

```

**Comment by btopro** [comment]
hmm.... so long as it would be against a single object you could do something like.....
```
<site-conditional truthy="{{__truthy}}" object="[[activeItem]]" conditions='{"title": "blogs", "author": "mike", "published": true}'>
  <instructor-bio-card></instructor-bio-card>
</site-conditional>
<site-conditional conditions="[[__truthy]]">
The else use-case.
</site-conditional>
```
object could be optional and if not defined, defaults to activeItem....

What do you think of something like that? Let's hash out the exact API / spec of what this should do before making it cause this could be another major step forward even though (I will say) conditional template rendering is generally discouraged due to performance. So doing them now and then for specific situations is fine but I've tried to limit my use of the `template is="dom-if"` method that I currently have access to.

**Comment by btopro** [comment]
LitElement is everywehre in our stack now and has logic for this so not sure what we'd be adding...
