### ISSUE TITLE
Confirm GitHub Publishing Works w/TFA

### ISSUE THREAD

**Issue by rickmanelius** [elmsln/HAXcms#132]
I attempted a simple clone, ddev start, add GitHub configs, create site, and publish. I'm not able to establish an initial connection and it's possible that it's either 1) user error or 2) I have TFA enabled and that blocks the connection from getting established by adding the public key.

**Comment by btopro** [comment]
so now when you hit "publish" it does the following:
- resets master (if theres no origin it doesnt fail)
- moves over to gh-pages branch
- publishes the files in the format needed, then doesn't reset the branch (important)
- attempts to push, if it fails doesn't fail on the front end
- sets back to master

This allows you to do the following:
- Work on HAXcms sites and "publish" which really is just creating a tagged version of the build in a gh-pages branch... even if there's no backend setup
- let you go into terminal on your own file system and push the files up for the branch successfully

This way you don't NEED to put creds or ssh key gen stuff into HAXcms yet it'll orchestrate the files the same (just won't ship them obviously). Then you can go in and ship them yourself.

**Comment by btopro** [comment]
```
<br />
<b>Fatal error</b>:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://api.github.com/user/keys` resulted in a `401 Unauthorized` response:
{
 &quot;message&quot;: &quot;Bad credentials&quot;,
 &quot;documentation_url&quot;: &quot;https://developer.github.com/v3&quot;
}
```

bad credentials is something that needs caught too. should provide some kind of "that didn't work :(" prompt to tell people  how to resolve the issue.

**Comment by btopro** [comment]
This won't fail miserably now. We were able to work out a workflow locally like this with someone recently:
- Setup the git info tho don't actually put in your key / password
- make a site
- hit publish
- when it claims to be done, go onto the file system and do
```
git checkout gh-pages
git push origin gh-pages
git checkout master
git push origin master
```
This will drive version control for you as well as for the gh pages branch while not requiring your password be entered

**Comment by btopro** [comment]
So this is a fun one to close because here's the commit that documented it :)

https://github.com/elmsln/haxtheweb.org/commit/8f14b92928f2411dfc9618087c670030c0d96398

https://haxtheweb.org/publishing now has a lot more documentation associated with whats happening and the steps to take as well as alternate publishing workflows
