### ISSUE TITLE
Docs should recommend updating bash first.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/HAXcms#156]
I had installation issues until I updated bash.

**Comment by btopro** [comment]
Local installs have reported issues with bash based on version. Odd cause what bash there is is minimalist but still worth noting. What version worked for you? I'm using 4.4

**Comment by btopro** [comment]
docs updated

**Comment by btopro** [comment]
also bash install (while still happening in ddev) is now optional thanks to #164 :) :)
