### ISSUE TITLE
[ux] Better error display: Attempting to create a new site throws a 403 Forbidden

### ISSUE THREAD

**Issue by mikecrittenden** [elmsln/HAXcms#20]
I tested out the Docksal setup and got this:

![2018-08-10 at 11 46 am](https://user-images.githubusercontent.com/32261/43967744-21c753f4-9c93-11e8-82ca-a98f01b9ada7.png)

**Comment by btopro** [comment]
Did you hit the power button in the top right? Login is admin admin. There are admittedly some state issues to improve there  😁

**Comment by btopro** [comment]
new login system works better tho we still need an error message but its not possible to get locked out now
