### ISSUE TITLE
Update MAMP docs to clarify

### ISSUE THREAD

**Issue by nikkimk** [elmsln/HAXcms#223]
Update this line of docs 

> Place HAXcms files in the htdocs folder of MAMP.

to 

>Extract the files from HAXcms-master.zip, copy the inner contents of the extracted HAXcms-master folder directly into the htdocs folder of MAMP.

**Comment by btopro** [comment]
docs updated to suggest both are possible as next publish will resolve this issue and either way will be acceptable
