### ISSUE TITLE
Installation error: Syntax error, unexpected '?'

### ISSUE THREAD

**Issue by JackWillDavis** [elmsln/HAXcms#263]
I installed HAXcms on a new PHP 5 LAMP (Bitnami) server on AWS Lightsail. I used the hands-off installer where I cloned the repo and then ran `install.php`. It showed me the HAX art and the username and password I'd need.

Installation seemed to go through OK, the `_config` folder was created fine and I can see there's all the setup in `config.json` but when navigating back to the home page I see the following error show up:

```
Array
(
    [type] => 4
    [message] => syntax error, unexpected '?'
    [file] => /opt/bitnami/apache2/htdocs/vendor/symfony/filesystem/Filesystem.php
    [line] => 560
)
```

**Comment by JackWillDavis** [comment]
Edit: I have a fix. I'll put it through as a potential PR now.

**Comment by btopro** [comment]
out of curiosity why did you pick PHP 5? All the 5.x's are beyond LTS unless you've got an older version of ubuntu your running that keeps this supported / other things on the same box that would need PHP 5 we've gotta start moving off of it -- https://www.php.net/supported-versions.php

**Comment by btopro** [comment]
Your PR I"ll assume is accurate but I'm not sure that we can / should patch the vendor directory since composer managed that (ugh I know... :) ). But I'l be curious to hear more of if Bitnami PHP 5 was intentional or just what you happened to pick.

**Comment by JackWillDavis** [comment]
Hi Bryan, it was just something we were going to install on a (sort of) spare server which is running Ubuntu 14/PHP5 as an internal wiki/Knowledgebase.

I did try on PHP7 and got the same issue. 

You’re right about the vendor file, it might be something we just use a patch for internally until we’ve played around with it more. Once the fixes were in place, we weren’t able to login due to a POST 403 issue but I’ll maybe have a proper mess around with it on PHP7 tomorrow and put through a proper PR if there are still issues.

**Comment by btopro** [comment]
Hmm ok, didn't realize it would be THAT php version specific. Wonder if it's using php 7.2 syntax or something. May need to hang onto patches then for broadest support (ugh). Did you apply the patch and then try in ddev/docker locally? I'm not against patching it just (as usual) gritting my teeth about symphony heh

**Comment by btopro** [comment]
php 7.1 is required for HAXcms apparently based on Symphony requirements. Kinda hard to patch and maintain when we'll be using more symphony in the future
