### ISSUE TITLE
Katrina's UX Audit

### ISSUE THREAD

**Issue by btopro** [elmsln/HAXcms#269]

**Comment by kat-wehr** [comment]
- [ ] Be able to change/update course name (site name) 
- [ ] Image moving - currently it only moves to the top or bottom however if you move things around the image they move spot by spot
- [ ] Sub pages don't get renamed properly in URL

**Comment by kat-wehr** [comment]
- [ ] Difference in spacing while editing vs what it looks like when saved/published

**Comment by kat-wehr** [comment]
- [ ] When trying to format text in paragraphs, clicking the buttons (example, bold or italicizing) doesn't do anything. Formatting can be added in source view and it works then.

**Comment by kat-wehr** [comment]
- [ ] Add field for placeholder details so the next person in the workflow (IPS/video person, QA, etc) knows what's supposed to go there.

**Comment by kat-wehr** [comment]
>     * [ ]  Be able to change/update course name (site name)


UPDATE - this actually is possible by using the gear icon when editing within the site, BUT it would be nice if we could better control what shows up in the upper left corner. ex if I wanted the course name "GD 110" and also the title, they should be displayed in a way that doesn't squish them together.

**Comment by btopro** [comment]
![2019-06-07_15-51-05](https://user-images.githubusercontent.com/329735/59130105-85f54e80-893c-11e9-893e-1770221f5f0b.png)

**Comment by btopro** [comment]
sub-page renaming is related to #57 path name can be automatically set via the "pathauto" setting under advanced. So the capability is there but we'll just need to clean up the UX / whether that happens automatically or not. I can see situations where automatically updating it after the fact could be problematic if internal pages references that path directly sorta gig.

![2019-06-27_10-57-38](https://user-images.githubusercontent.com/329735/60276851-68c3f800-98ca-11e9-8c4b-6a2558909828.png)
