### ISSUE TITLE
Swagger document the API backend

### ISSUE THREAD

**Issue by btopro** [elmsln/HAXcms#276]
https://swagger.io/tools/swagger-editor/

We should do this for the structure of the appstore as well but first you it would be great to document how we talk to the php engine. This is the first step toward refactoring the data connectivity as well as creating an express based backend. And that Joe Moore will love us.

**Comment by ThatJoeMoore** [comment]
![For me?](https://media3.giphy.com/media/KQm5O05y9rzQA/giphy.gif?cid=19f5b51a5d03058131776d4436ad45e7&rid=giphy.gif)

**Comment by btopro** [comment]
Swagger is now generated using a php class engine. Here's an example of the output https://gist.github.com/btopro/c807a057f029f30f2a46a8c97a718bef

When the new release comes out, we'll be able to access `/system/api` or `/system/api/openapi/json` and obtain an OpenAPI 3.0.0 conforming document in YAML or JSON format. All APIs are currently tagged, described and surfaced via this output but they still need their properties / usage / response examples fleshed out further.

Closing this for now as it's a huge step forward and in place for 1.0.0 :)
