### ISSUE TITLE
Default scale-50 on image uploads is confusing

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#288]
I did my first page with an image; no problem uploading image and configuring alt-text but the image is not displaying as expected. I want the image to display at the full size (no resizing needed), and it looks good in the editing window, but then in the browser it is distorted. Not sure if if this is a bug, or if there is something I need to do for an image to display just as-is without any resizing? 
Page:
https://hax.lauragibbs.net/sites/story-folder/s000014
Image URL:
https://hax.lauragibbs.net/sites/story-folder/files/scale-50/Screen%20Shot%202019-06-18%20at%203.30.55%20PM.png
Screenshots: editing window; looks good!

![Screen Shot 2019-06-18 at 4 06 23 PM](https://user-images.githubusercontent.com/19476543/59716224-9b436600-91e3-11e9-9d4e-4562b92d91d8.png)

Display; image is being resized...?

![Screen Shot 2019-06-18 at 4 11 09 PM](https://user-images.githubusercontent.com/19476543/59716281-b7df9e00-91e3-11e9-8a3b-b8bb64b30225.png)

**Comment by lauragibbs** [comment]
I tried playing with the image and it still wasn't working; I deleted the image and uploaded a new version, 600 pixels wide. I think the problem might have something to do with this "scale-50" that is showing up in the URL. That scale-50 thing shows up automatically when I upload the image as the URL, and it's also in the HTML view of the page:
<img src="files/scale-50/buzzard2.png" alt="musical notes for the buzzard's song"/>

image file that I uploaded, 600 pixels wide (352 pixels height):
![buzzard2](https://user-images.githubusercontent.com/19476543/60130736-d60a4880-9765-11e9-9599-ea6fd1158b3b.png)

image as shown in the editor does look like it might be 50% version of my original?
![pubview](https://user-images.githubusercontent.com/19476543/60130764-e5899180-9765-11e9-9d47-4081d868b65b.png)

here's how published page looks: I'm really not sure at all what's going on here...?
![editorview](https://user-images.githubusercontent.com/19476543/60130746-dd315680-9765-11e9-9e18-343d189b2e66.png)

For a default, it seems like it would make sense to default to displaying 100% my original image, and then I would adjust that using the slider and/or by entering a fixed number for width or height...?

**Comment by btopro** [comment]
ahhh I see. If you take the scale-50 out of that URL you'll have your original image. We've got it in there currently as a way of hoping people don't drag and drop upload full resolution images and tick off their users.

**Comment by lauragibbs** [comment]
oh yay, that's great: I'll go see if that works. I prefer to resize myself rather than resizing in the browser.
it's still kind of buggy in the sense that it was going to that scale-50 by default. I'll manually take it out and see if that does it. thank you!!! :-)

**Comment by lauragibbs** [comment]
PERFECT!!! I just removed that scale-50/ 

![Screen Shot 2019-06-25 at 6 14 51 PM](https://user-images.githubusercontent.com/19476543/60137531-36ed4d00-9775-11e9-93bc-2ea5ce397eaf.png)

**Comment by btopro** [comment]
Yeah, @nikkimk might have an idea for how we want to handle this. I know it came up in discussion w/ @heyMP the other day (notion of scaling / having something process media).

@nikkimk for context here, when user's upload images we default compress a thumbnail as well as do a scale-50 transformation to them. All 3 (original, and these two derivatives) are stored when you upload something but we default to the scale-50. How do you think we should handle this? Not do any of them and then create a way on the front-end to like do a drop down and pick defaults like this or something else where we can process things in bulk? Not sure the UX pattern for this as @lauragibbs is certainly not our typical IDs who will upload a 5 meg image uncompressed at times.

**Comment by btopro** [comment]
@nikkimk do you think some kind of file variants array could be used in what your currently doing w/ the HAX schema + eco json forms UX improvements?

This seems like it's almost a flavor of an upload... not sure. It's like we want the user to upload something and then make a decision / let them easily toggle how they handle the variants of that file. Another possible related example in the future is @heyMP has talked about upload and pandoc microservice saying "TXT file... cool, how do you want to use this though?" and allow click and convert it on the fly from whatever to whatever. Almost like "I gave you a word doc but I want to present it as a PDF" and having that be a toggle.

Does this seem like a UX convention possibly required of the uploader element or something else?

**Comment by btopro** [comment]
fixed. now we just default to the thing that's expected
