### ISSUE TITLE
Installation on LAMP server

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/HAXcms#290]
Just some feedback when I was setting this up on a fresh LAMP stack with PHP 7.3. I initially had HAXcms files unzipped into /HAXcms-0.8.2/* and navigated here in my browser, however when clicking 'Click here to take me to my sites' it just refreshed the page and never went anywhere. 

After I ran the bash script `bash scripts/haxtheweb.sh` this then seemed to force it through onto the login page. However after I tried to login there was a system error because it couldn't find `/system/login.php`. I realised it was looking for this in the web root, rather than within `/HAXcms-0.8.2/`

I moved all files and folders into the webroot and navigated there in the browser. Again, it didn't seem to do anything when I clicked the link, so I ran the bash script again, this worked and so did the login :)

**Comment by btopro** [comment]
huh... interesting. My guess is that you put it in a folder and that the web server didn't have write access on the directory. When I throw things up in MAMP they pull in just fine but I'll fire up a digital ocean box now and see what the install flow is like there.

Thanks for the report

**Comment by btopro** [comment]
ok, it would appear to be a write access issue so I should probably test on install that there is write access as part of claiming to have been installed, instructing what to write to help fix the issues or to run the installer on the server

**Comment by btopro** [comment]
a message shows up saying that it needs write access now or to run the bash script.
