### ISSUE TITLE
500 error when saving content

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/HAXcms#292]
When I edit and then save the system responds with a 500 error from `/system/saveNode.php`. There's a further object error from `haxcms-site-editor.js`:

```
Error: The request failed with status code: 500
    at HTMLElement.<anonymous> (https://site.co.uk/sites/b-hive-developer-documentation/build/es6/node_modules/@polymer/iron-ajax/iron-request.js:1:2112)
```

However, when I refresh the page the updates do actually get saved

**Comment by btopro** [comment]
hmmm.. is this possibly related to the #294 issue or is this still happening?

**Comment by rickhumphries** [comment]
This one's still happening. Happy to share server details on the back channel if that's easier to look at

**Comment by btopro** [comment]
can you open the dev tools and look in the XHR section on network. Issue a save and then click and see what it claims the response is. It's possible it's spitting out an error message yet is saving. HAXcms requires PHP 7.1+ so that could also be part of it

**Comment by rickhumphries** [comment]
```
Request URL: https://bc-docs.co.uk/system/saveNode.php
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 176.58.123.228:443
Referrer Policy: no-referrer-when-downgrade
Connection: close
Content-Length: 642
Content-Type: application/json
Date: Wed, 26 Jun 2019 14:37:26 GMT
Server: Apache/2.4.25 (Debian)
accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Content-Length: 873
content-type: application/json
Host: bc-docs.co.uk
Origin: https://bc-docs.co.uk
Referer: https://bc-docs.co.uk/sites/b-hive-developer-documentation/ndp-audit-1/issues
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
{siteName: "b-hive-developer-documentation",…}
body: "<p>Issues will be logged here - <a target="_blank" href="https://github.com/rickhumphries/bc-devdocs/issues">https://github.com/rickhumphries/bc-devdocs/issues</a>↵↵↵</p>↵"
jwt: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6InBWRFExb1o4NjM0M29jVVNNRU12dFllTWpVRXgzdm9TNTV5LXM4NmdWMFEiLCJ1c2VyIjoiYWRtaW4ifQ.T8NbPNVz4WVWcbgGhQxRnunuaSrS92LsPF4gq6u_Zp4"
nodeId: "item-9f3c25db-9ce9-4f80-b9c5-0e4842189b34"
schema: [{tag: "p", properties: {,…},…}]
siteName: "b-hive-developer-documentation"
```

**Comment by rickhumphries** [comment]
I updated to the latest version of PHP so it shouldn't be linked to that

**Comment by btopro** [comment]
Can you post the response not the headers section (tho those look ok)

**Comment by rickhumphries** [comment]
ah sorry
```
<pre>Array
(
    [type] => 1
    [message] => Uncaught Exception: "/var/www/html/_sites/b-hive-developer-documentation" is not a git repository in /var/www/html/system/lib/Git.php:282
Stack trace:
#0 /var/www/html/system/lib/Git.php(237): GitRepo->set_repo_path('/var/www/html/_...', false, true)
#1 /var/www/html/system/lib/Git.php(103): GitRepo->__construct('/var/www/html/s...')
#2 /var/www/html/system/lib/HAXCMSSite.php(143): Git::open('/var/www/html/s...')
#3 /var/www/html/system/saveNode.php(107): HAXCMSSite->gitCommit('Page updated: I...')
#4 {main}
  thrown
    [file] => /var/www/html/system/lib/Git.php
    [line] => 282
)
</pre>
```

**Comment by btopro** [comment]
hmm... interesting. I wonder if there weren't permissions to do this. if you ssh to the server and go to the directory in question and type `git init` this should go away. Curious what the on box settings are that it wasn't allowed to make the git directory... hmm

**Comment by rickhumphries** [comment]
yep that command works. I got a `-bash: git: command not found` message when first running it and so had to run `sudo apt-get install git` first which could explain it?

**Comment by btopro** [comment]
aaahhh yes that's it! So, what server config was this? It would be good for us to have stuff like that already in the install script in the event that people don't have dependencies like that. If they do then it doesn't hurt to include as well

**Comment by rickhumphries** [comment]
It was a one click LAMP stack on Linode which is Debian 9. In my case (and I read that in most cases) a lot of the one-click installs through cloud hosting providers also only setup PHP 7.0 too

I'd read about HAXcms only supporting 7.1+ so I updated to PHP 7.3 but it wasn't as straightforward as I thought it might be to do that.

**Comment by btopro** [comment]
that makes sense. we're in this odd space where PHP 7.0 just was deprecated recently -- https://www.php.net/supported-versions.php

yet is still the default in a lot of things that fire up.

Here's what HAXiam currently includes to get going on Ubuntu 18 -- https://github.com/elmsln/HAXiam/blob/master/scripts/ubuntu18.04.sh#L33-L49
