### ISSUE TITLE
Migrating Pages from one setup to another

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/HAXcms#293]
I created a few pages on a local setup that I thought I'd move to the live site I've got now. I copied the folders from one `_sites/site/pages` directory to the other on the server via FTP but I then couldn't get them to show up in the site. Are there any additional steps required?

**Comment by btopro** [comment]
Yes, the site.json file is the piece that actually has the relationships between pages and how to present them. Think of it like drupal's book database table that outline designer is interfacing with to structure material and `pages/` at some level just being the node body db table :)
