### ISSUE TITLE
404 Error when refreshing or navigating directly to specific page

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/HAXcms#294]
I always receive a 404 error message when navigating to a specific page by copying/pasting the link into a browser, or refreshing a page I'm currently on. I always need to navigate directly to the site's homepage, then use the navigation pane to move to specific pages

**Comment by btopro** [comment]
this is an apache config issue. The server has to allow local directives much like Drupal does. Something like this:
```
<Directory /PATH/TO/THE/HAXCMS/ROOT/FOLDER>
    AllowOverride None
    Order allow,deny
    allow from all
</Directory>
# CDN module / static domain support
<VirtualHost *:80>
    DocumentRoot /PATH/TO/THE/HAXCMS/ROOT/FOLDER
    ServerName HAXCMSDOMAINNAME.COM
</VirtualHost>
```

**Comment by rickhumphries** [comment]
Ah yeh that's better. In `/etc/apache2/apache2.conf` there was:
```
<Directory /var/www>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>
```

Changing `AllowOverride` to 'All' fixed it

**Comment by btopro** [comment]
This would be good to have in an install guide for haxtheweb.org
Here's something fun. You could fork this repo GitHub.com/elmsln/haxtheweb.org then pull it local on your computer and edit it in haxcms locally. Push it back up to GitHub and then issue a pull request.

I'm not saying you have to but as this theoretically is possible it would be cool to see the workflow play out and figure out how we can streamline it

**Comment by rickhumphries** [comment]
Yeh OK I'll give it a go

**Comment by btopro** [comment]
bottom of https://haxtheweb.org/installation now

**Comment by btopro** [comment]
putting this into the ubuntu 18 installer automatically as it's required now bc of the way we do paths
