### ISSUE TITLE
Full-Text RSS Feed... even better: full-text with media

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#297]
This is a request for something like full-text RSS feed. With blogs, I am used to being able to get an RSS feed that contains the full text plus media (images, embedded video). I use Inoreader as my RSS feed reader, and I can also then use Inoreader to syndicate that output, combining feeds, filtering, etc.

So, for example, here's a typical RSS feed coming out of one of my blogs:
https://olebrerrabbit.blogspot.com/feeds/posts/default

I subscribe to that feed in Inoreader, along with subscribing to all my other blogs, and then I can combine those RSS feeds into a single feed at Inoreader:
https://www.inoreader.com/stream/user/1005987531/tag/Laura%20Blogs
That's an RSS feed combining the RSS from about 20 different blogs that I work on. I can also get that as HTML from Inoreader, magazine view:
https://www.inoreader.com/stream/user/1005987531/tag/Laura%20Blogs/view/html?cs=m
Or full view:
https://www.inoreader.com/stream/user/1005987531/tag/Laura%20Blogs/view/html

So.......... if I could get RSS coming out of my Hax site, I would be able to subscribe with Inoreader and fold that into the combined feed of all my other blogs. That would really only make sense if I had full text thought; right now, this truncate RSS feed is not very useful (at least not for me, where my goal is syndicating the content in other spaces).

For example, I syndicate the combined content of all my different blogs here:
http://mythfolklore.net/
That's my "home page" online, and it shows my latest three blog posts across all those different blogs. It would be so cool if my Hax site could be included there too.

**Comment by btopro** [comment]
#192 is related as having a primative map would allow us to ship media hidden in webcomponents out via RSS and to the legacy mode of the site more true to their form even if the advanced players and visual capabilities of some elements arn't used.

Great idea Laura. Would you want full text of ALL items or just the latest / some variable amount? We are trying to balance static / permanence w. Things like this that are best served from a dynamic backend (server running PHP).

**Comment by lauragibbs** [comment]
Oh, just newest items is all anyone expects from RSS! So if there were just 20 or 25 items (most recent) would be great. Blogger has 25 most recent items in its RSS feed I think, and I just checked Diigo; they have 20 most recent items. Here's a Diigo feed example where you can see how they just do 20:
https://www.diigo.com/rss/user/laurakgibbs?key=5af583f8fdff82a8ba417ffd4944f88d&query=%23summary%3Ayes&sort=created

**Comment by btopro** [comment]
commit added 25 item max, full HTML in response, and correct dates / sort order for RSS output (and ATOM feed). It won't include the full media currently bc of the webcomponents which needs  #192 in order to ensure that non-JS based versions will still get the material, unless there's a way of shipping RSS w/ javascript included that won't break things but I highly doubt RSS lets `<script>` tags float with it for security :0)

**Comment by btopro** [comment]
#192 is a blocker for the media inclusion but at least we've got full text in the right order now
