### ISSUE TITLE
Airtable integration

### ISSUE THREAD

**Issue by michael-collins** [elmsln/HAXcms#303]
I've been using Airtable to mock up my course assignments and grading structure recently. If you haven't used it, it's essentially a really good UI for a relational database/spreadsheet similar to smartsheet, but with extensive api support. This seems like a tool perfect for HAX integration, everything is json :)

To show a use case, I mocked up a feedback system similar to the elms studio feedback tool @nikkimk and I talked about forever ago, with pre-made feedback terms that you can pull into different categories. Using this to manage rubrics, and presenting things into a student-facing lms/site would be a killer use case.

<img width="1209" alt="Screen Shot 2019-06-28 at 12 37 53 PM" src="https://user-images.githubusercontent.com/1085304/60357422-99c32c00-99a1-11e9-93e1-1258b29e6f2f.png">

<img width="1316" alt="Screen Shot 2019-06-28 at 12 32 24 PM" src="https://user-images.githubusercontent.com/1085304/60357176-f3772680-99a0-11e9-8b8a-bac9104fff61.png">

**Comment by btopro** [comment]
that's cool, what would an integration look like in your mind? Ability to embed these via HAX?

**Comment by michael-collins** [comment]
Embed would be low hanging fruit. But fields integration would be truly awesome! Similar to hooking up content types to web components in Drupal. You can export and download the airtable data, so if you wanted permanence for archiving purposes, I think it meets that goal as well, though you'd need the option to point to and extract data in a file versus a rest call.

**Comment by btopro** [comment]
New issues opened around this and grade book takes into account these screenshots (and without airtable)
