### ISSUE TITLE
Unable to rename file? (hopefully someone can tell me how to do this)

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#304]
I'm not sure how to describe this problem.

I have a page, S000045, and I can see in the sidebar navigation (it's up at the top; not the order I want, but that's where it is). When I click on that link, though, it goes to this URL:
https://hax.lauragibbs.net/sites/story-folder/s000045-1

I'm not sure what's up with that, but it is going to mess up my records. I need that page to be s000045. I think this happened because the outline option was adding indents I did not want, and when I removed the indents, the navigation went kablooey and that page ended up at the top of the navigation.

When I go to the URL that should be the URL for that page, I see the "about" page I made for the site:
https://hax.lauragibbs.net/sites/story-folder/s000045

I hope this is fixable! Let me know what I can do so that I can carry on with my file names. I need to be able to DELETE s0000045-1 and be able to edit s000045. At the moment, I'm hesitant to click the edit button at that url -- https://hax.lauragibbs.net/sites/story-folder/s000045 -- because I don't want to overwrite the about page that I see displayed there (and I'm able to edit the about page separately).

I've left story 45 out of the "about" listing for now until somebody can tell me how to fix this. Thanks for your help!

**Comment by lauragibbs** [comment]
I forgot to say that I'm perfectly happy to have https://hax.lauragibbs.net/sites/story-folder/s000045-1 deleted! 
I have all the content in a GoogleDoc.
I just need to know how I can access https://hax.lauragibbs.net/sites/story-folder/s000045 so that I can safely re-enter the content there. :-)

**Comment by btopro** [comment]
so the way that that paths work is that if it doesn't know what the path is it goes to the home page (aka 1st page). So, it looks like there is no s000045 and thus defaults back to the main page.

To change the url, go to the page in question and click on the thumb print for "details"
![2019-06-30_21-56-21](https://user-images.githubusercontent.com/329735/60406078-2298be00-9b82-11e9-8d82-7d69c89ec2b9.png)

Then you should see a pop up with something like this in it and the thing you want to change is Location:
![2019-06-30_21-58-35](https://user-images.githubusercontent.com/329735/60406104-478d3100-9b82-11e9-8c84-eb04927f7f35.png)

hit Save Fields and it should reload and make the path what your looking for.

**Comment by btopro** [comment]
There's also a "pathauto" setting that will automatically control the names of things to match the titles / nesting them when things are in hierarchies but I'm not positive this is what you want. If you want the page title to update to be in sync with the url then you'd do the following:
- blue arrow, click on 
- then, green arrow click "advanced"
- last click pathauto (red arrow) and then hit Save Fields.

Now it should automatically update all urls when you save things to keep the title in sync w/ the address.

We've debated if this should happen automatically or not but for use cases of other faculty that want vanity URLs it can be confusing (like you want the page to say Welcome to my course but the url to be syllabus as 1 example).

**Comment by lauragibbs** [comment]
Aha, super: I will learn something new! Thanks for the info, and I'll leave a note here when I plunge back in tomorrow. :-)

**Comment by lauragibbs** [comment]
I could not get the Path solution to work, so I went ahead and documented what happened in case that will be useful. When I try to manually change the path for my existing S45 page, it just changed it from -1 to -2 as you can see in the screenshots below.

I click on details for my S000045 link in the index
![1](https://user-images.githubusercontent.com/19476543/60449810-7513c200-9bf6-11e9-98a3-7224ce4a3132.png)


I changed the path to remove the -1 to give the path I want:
![2](https://user-images.githubusercontent.com/19476543/60449814-7644ef00-9bf6-11e9-8122-62e044f3f250.png)


But all it did was change the -1 to -2:
![3](https://user-images.githubusercontent.com/19476543/60449817-78a74900-9bf6-11e9-91c0-ab66f87482f9.png)


If I start by going to the s000045 URL and click on the details option, it really looks like it is showing me the about page information, and I don't want to mess with that.

It looks like the system somehow thinks I am already using s000045 and it will not let me use it again, so for my own safety it is adding -1 and -2 to the path. I really need to use that s000045 URL. Is there something I can do by going into the File Manager and manually deleting a file or something?

Here's what I see for the https://hax.lauragibbs.net/sites/story-folder/s000045 URL. That really looks like it is editing my about page; I don't want to mess that page up:
![4](https://user-images.githubusercontent.com/19476543/60449840-852ba180-9bf6-11e9-90e1-c7a920e77058.png)

FWIW my other pages look fine, no problem with path and title matching:
![Screen Shot 2019-07-01 at 11 52 16 AM](https://user-images.githubusercontent.com/19476543/60450101-1864d700-9bf7-11e9-99d7-4c9b40860eca.png)

**Comment by btopro** [comment]
Rename improved as part of the data clean up in the outlining tool so closing this for now
