### ISSUE TITLE
having to hit Control-Shift-R way more often today

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#307]
I'm not sure what's going on today as I'm having to hit Control-Shift-R to make pages display properly A LOT today. I have to do that occasionally, but today it's been pretty intense; it seems like I'm having hit Control-Shift-R for every page, and to do so repeatedly. I'm not sure why today would be any different than usual: I follow exactly the same procedure in the same browser on the same computer every day for adding and editing my 5 new pages.
One thing I noticed is a strange double highlighting in the index sidebar, so I've attached some screenshots in case that is any help. For all three of these pages, the content has been added, page saved, and site republished repeatedly, so I have no idea why the content is not showing up. When I do the hard refresh, the page shows up properly, but people who come to the site via a link are not going to know that they have to do a hard refresh to see the content (if that is what they experience...? I don't know; I'm just seeing that I have to do the hard refresh again and again today).

I'll report back tomorrow about whether this strange behavior is ongoing.

Here are some screenshots that show the weird ghost highlight in the index sidebar; I can't see any particular rhyme or reason to what's being highlighted:

![Screen Shot 2019-07-06 at 11 15 10 AM](https://user-images.githubusercontent.com/19476543/60758017-f1841780-9fdf-11e9-89d1-9040b2b3ee90.png)
![Screen Shot 2019-07-06 at 11 15 34 AM](https://user-images.githubusercontent.com/19476543/60758019-f47f0800-9fdf-11e9-871e-378b275708a4.png)
![Screen Shot 2019-07-06 at 11 15 49 AM](https://user-images.githubusercontent.com/19476543/60758022-f8128f00-9fdf-11e9-8f31-6fce5b32eee8.png)

**Comment by lauragibbs** [comment]
I just thought I would try this one more time (it's about an hour later), so here's one of those same URLs that I was having problems with before:
https://hax.lauragibbs.net/sites/story-folder/s000075

Even though I have force reloaded the site, the content is still not showing up:

![Screen Shot 2019-07-06 at 12 16 41 PM](https://user-images.githubusercontent.com/19476543/60758691-3744de00-9fe8-11e9-988f-9bf53717e13a.png)


But when I do a hard refresh with Control-Shift-R, it works. But most users are not going to know to do that, and I'm not sure why I should have to do that at all...? And repeatedly? Hopefully this is actually a bug somewhere that can be fixed and not a normal behavior. Fingers crossed!

![Screen Shot 2019-07-06 at 12 17 01 PM](https://user-images.githubusercontent.com/19476543/60758694-3ca22880-9fe8-11e9-8fe8-0928ede3d8f5.png)

**Comment by lauragibbs** [comment]
No problems with the site loading today. I wish I could figure out why there would be that variability from day to day. I follow the same procedure, same computer, same browser. But something was making things very sticky yesterday. Everything went super-smooth today and just clicking on links at random in the sidebar and from the about page, all the pages are coming up as expected, no reloading required. Yay! I don't know if you want to close this or not; if I run into problems like I had yesterday again, I will update. :-)

**Comment by lauragibbs** [comment]
Well, I posted too soon. I was about to go share a page from the HAX site at Twitter, and I clicked through from my Diigo listing, and I got the default blank page, plus ghosting in the sidebar... here is the link via Diigo, and here is the screenshot. I have no idea why I would have to reload the site, but maybe it will help in troubleshooting to know that the link came from Diigo (and I really need those links to work...):
Diigo page:
https://www.diigo.com/user/laurakgibbs?query=%23hax
Link via Diigo:
https://hax.lauragibbs.net/sites/story-folder/S000080
Screenshot of result (I've click through from Diigo three times to make sure; it happens every single time), with the same ghosting that shows both S000080 and S000063 highlighted:

![Screen Shot 2019-07-07 at 11 32 11 AM](https://user-images.githubusercontent.com/19476543/60770641-40e34a00-a0ab-11e9-9977-91069fde31c4.png)

So, after trying three times and running into the same problem. I hit Control-Shift-R to force the refresh. When I do that, the page appears correctly, but when I go back to Diigo and click through, I get the same error page.

This is a serious problem; I don't know what is happening, but I need those links from Diigo to work. The whole idea of this site is that it is a reference site that people will access via links that come to the site from other places. Hopefully there is a fix! After I hit Control-Shift-R, the page looks fine... but people will not know that they have to hit Control-Shift-R to load the page, and they should not have to do that. Help!

**Comment by lauragibbs** [comment]
I thought I would give it another try, so I went to Diigo and clicked on the link:
https://hax.lauragibbs.net/sites/story-folder/S000080

Still no content, but no ghosting in the sidebar. I'm baffled, esp. by the inconsistency. 

![Screen Shot 2019-07-07 at 2 23 52 PM](https://user-images.githubusercontent.com/19476543/60772345-07b6d400-a0c3-11e9-99c9-78b86b4f825a.png)

For troubleshooting, I tried these other things:

Firefox on my desktop. The link works fine! Looks just how it is supposed to look.

Chrome on my phone. Clicking on the link does absolutely nothing; the screen just sits there on the About page. I'm not sure what the equivalent of Control-Shift-R is on my phone, but I cleared the cache in Chrome, but the link still does not work. None of the links from today work, although a link from yesterday does work:
https://hax.lauragibbs.net/sites/story-folder/S000075
(but S000076, S000077, S000078, S000079, S000080 do not work; the screen just sits there as opposed to the scroll-and-display behavior I get with the other links).

So, I powered my phone off and then on again; now the links are working.

I'm going to keep on adding content on the assumption that this is just some refresh problem... but I can't share links with confidence right now. I hope there might be some easy/obvious solution. This is not a problem I've ever encountered with web publishing before so I don't know what to look for or how to troubleshoot. If there is anything I can do/test, let me know!

**Comment by btopro** [comment]
It is a refresh problem and it's something that I believe the next release addresses. Basically your machine goes "oh, site.json, I'll cache that" which is the file that has the whole index of what links are valid. It's trying to serve as fast as possible which is kinda the HAX static site way.

However, in non "published" setups like what your doing you've basically got a dynamic website people expect to go to and have things be there instantly. Opening #310 as a result.

**Comment by lauragibbs** [comment]
AHA, site.json.
New in my vocabulary! If it's not a huge burden to not be cacheing that, I will be much relieved. It feels weird to have a link that I know for sure is good but have it not be working.
I won't post any more of my experiences with the refresh here until you let me know that there's a fix in a new release, and then I will bang away at it on my different devices to make sure the site.json is happy. THANK YOU.
I am getting a serious heap of stories going in here, and the resulting webpages are super. I also learned how awesome it is to read on my phone when I was testing that earlier today. The mobile view is fabulous: SO READABLE.
