### ISSUE TITLE
Documentation for creating/adding webcomponents to HAXCMS

### ISSUE THREAD

**Issue by LawlietBlack** [elmsln/haxcms#31]
Sorry if this is posted elsewhere, but I haven't been able to figure out how to add custom components to HAX/HAXCMS. Some additions to the documentation for this would be great!

**Comment by btopro** [comment]
completely agree. HAXCMS goal is to be minimal backend and have http://github.com/lrnwebcomponents/hax-body do all the heavy lifting.

The way elements get added in HAX is via the appstore specification it implements -- https://github.com/lrnwebcomponents/hax-body#can-i-build-my-own-elements-for-hax

In HAXCMS this is generated here https://github.com/elmsln/haxcms/blob/master/system/generateAppStore.php and currently needs a way of adding additional elements in and documenting this. Part of this workflow change has been on hold until we switch from bower (currently powering HAX) over to NPM.

https://github.com/elmsln/wcfactory is our efforts towards building out that catelog and has support baked in for automatically wiring new custom elements up to HAX.

It's a lot to take in, we know we need documentation for sure. HAXCMS is going to be what powers and replaces the haxtheweb.org mini-site and provide documentation (using the system itself as a vehicle). Once we get to that point all will start to shake out.  Always looking for people to help contribute and letting us know what questions we need to answer goes a long way towards this so thank you.

**Comment by btopro** [comment]
#33

**Comment by btopro** [comment]
Closing in favor of #33 which will work toward documenting this. We've switched to ES Modules so we can bother to document things like this now
