### ISSUE TITLE
[bug] Content Outline Deleting Metadata

### ISSUE THREAD

**Issue by cgldevel** [elmsln/haxcms#32]
When creating a new page through the outline UI, json metadata is removed from existing pages in site.json.  For example, I created a page called, "News" and then nested a News post under it w/ the following structure:

```
{
      "id": "item-5643c669-454b-4789-b91b-37d69980deeb",
      "indent": 1,
      "location": "pages/item-5643c669-454b-4789-b91b-37d69980deeb/index.html",
      "order": 1,
      "parent": "item-01619e09-3dbb-491d-b85e-308340724bc6",
      "title": "5 Web Accessibility Tips for Developers",
      "description": "",
      "metadata": {
        "created": 1541517755,
        "updated": 1541517755,
        "type": "news",
        "template": "news",
        "image": "assets/odl-news-images/news-image-1.png",
        "author": "Charles Lavera",
        "authorImage": ""
      }
    },
```

When creating another News post - the metadata on the previous post is lost and the following code appears in site.json.

```
{
            "id": "item-e655aaad-0800-4c8d-a3c6-c042e0c8acd9",
            "indent": 1,
            "location": "pages\/item-5643c669-454b-4789-b91b-37d69980deeb\/index.html",
            "order": 1,
            "parent": "item-c4fcef9a-2969-40fa-9952-a58e3be5c810",
            "title": "5 Web Accessibility Tips for Developers",
            "description": "",
            "metadata": {
                "created": 1541775958,
                "updated": 1541775958
            }
        },
        {
            "id": "item-3a52a8bd-ab06-4879-8e60-fd5b30fae0b9",
            "indent": 1,
            "location": "pages\/item-3a52a8bd-ab06-4879-8e60-fd5b30fae0b9\/index.html",
            "order": 2,
            "parent": "item-c4fcef9a-2969-40fa-9952-a58e3be5c810",
            "title": "What do I Need to Know About the Universal Design for Learning (UDL) Framework?",
            "description": "",
            "metadata": {
                "created": 1541775958,
                "updated": 1541775958
            }
        },
```

**Comment by btopro** [comment]
hmm... based on what your showing me the ID is different for some reason in the 1st item. It's item-5643c669-454b-4789-b91b-37d69980deeb on first pass but 2nd it's changed. Maybe there's something happening in the logic that sends this along that is assigning IDs everytime. I've checked on specific metadata filtering and I have a whole thing about "metadata can be anything" so it's not that i don't think.

**Comment by btopro** [comment]
so it was two issues in one. 1 the ids were cycling incorrectly. 2 it was deleting everything in metadata and then rebuilding it. Now it preserves this data correctly when submitted via the json outline editor. Don't pull code tho @cgldevel until your ready to get on ES module workflow :)
