### ISSUE TITLE
very strange problems with the Outline navigation

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#321]
So I followed Bryan's advice and only used the click-click-click of the Outline mode to rearrange the pages. This took about a gazillion clicks, but I have it more-or-less cleaned up... although something really weird has happened.

I created a reading unit (that is the new experiment), with a starting page R0001 and an ending page, R0001end.
https://hax.lauragibbs.net/sites/story-folder/r0001
https://hax.lauragibbs.net/sites/story-folder/r0001/r0001end
I clicked up to move the stories into the unit, indented them, and also indented the ending page. 
It looks good in the outline, and it looks good in the site navigation bar. Screenshots:

![Screen Shot 2019-07-15 at 3 14 16 PM](https://user-images.githubusercontent.com/19476543/61242276-4a0b9100-a713-11e9-9249-54ceae963cba.png)
![Screen Shot 2019-07-15 at 3 14 33 PM](https://user-images.githubusercontent.com/19476543/61242279-4b3cbe00-a713-11e9-8f15-a563c8765102.png)

===============

Then I created another new page, Stories, and indented all the other stories under that. It also looks good in the site navigation and in the outline.

===============

So, the reading unit looks good in the sidebar and in the outline, but when I click using the sidebar link to the first page in the reading unit, which should be Story93, it goes to Story 113, which is the next page in the navigation, not the one I clicked on.

The little round button navigation is also not working: when I am on the Reading Unit page, 
https://hax.lauragibbs.net/sites/story-folder/r0001
I though that if I clicked on the "forward" button, it would go to the first story in the reading, Story93, but instead it goes to Story113 AND the URL is showing s000118.

And when I look in the Developer view, things are totally weird; the page titles and locations do not match. I only used the buttons in the Outline mode to move things up and down and to indent, so I am not sure how that mismatch happened, and I have no idea how to fix it, although it seems to be consistently one story out-of-order somehow. Here's a screenshot:

![Screen Shot 2019-07-15 at 3 12 20 PM](https://user-images.githubusercontent.com/19476543/61242818-ab802f80-a714-11e9-9832-e5ef1a285951.png)

===============

I'll assume it is safe for me to keep adding story pages (if not, let me know!), and I hope you can help me with the navigation. I don't care about losing the work I did to set up the reading unit; if you need to just reset the whole page ordering so that I can start over with the re-ordering, I can do the gazillion clicks again in the outline mode to set it up again. I like the way it looks now in the sidebar navigation, but something clearly went wrong as I did the gazillion clicks in the Outline mode to get the pages semi-organized.

**Comment by lauragibbs** [comment]
One more screenshot to show how the URL is not matching up with the page being displayed / highlighted in the sidebar:
the URL says https://hax.lauragibbs.net/sites/story-folder/s000094
which is indeed the story BUH FOWL-HAWK AND BUH ROOSTER
but the navigation is highlighting s000103, and S000103 appears at the top of the page. (But S000103 would be BUH WOLF AND THE TWO DINNER).
The links coming in from Diigo work fine and display correctly for both stories (you can see what I mean with this link: https://www.diigo.com/user/laurakgibbs?query=%23haxtest); I'm only having this problem when I use the sidebar navigation and the buttons in the HAX site. So I guess the pages are all good; something is just wrong with the navigation set-up...?

![Screen Shot 2019-07-15 at 3 27 01 PM](https://user-images.githubusercontent.com/19476543/61243099-37925700-a715-11e9-95ac-55e5c5f7e3d5.png)

**Comment by lauragibbs** [comment]
Perhaps one more clue: I rebooted my computer completely, cleared my Chrome browser cache, and when I went to the site, 
https://hax.lauragibbs.net/sites/story-folder/
I saw an old version, not the current version, so I did the force reload
And this is what I see when I force reload... so perhaps this is related to my set-up at Reclaim again? This is the problem I had when originally installing HAX. Plus the navigation display here is even more weird (not the same as what I see when I look at the site in Firefox, where it is loading fine), so I have no idea what's up with all this. But it seemed like it might be a good clue.
You can let me know what I should do/check next.

![Screen Shot 2019-07-15 at 3 45 41 PM](https://user-images.githubusercontent.com/19476543/61244281-db7d0200-a717-11e9-91d5-ffb14b455a70.png)

**Comment by lauragibbs** [comment]
Per a Twitter convo with Charles Lavera (thank you!), I am going to try editing the json file to get the navigation back in whack. Wish me luck! I am going to learn a lot anyway. :-)

**Comment by lauragibbs** [comment]
Okay, I fixed the outline/developer mode view so that there is no more discrepancy between the title and location, so that's a relief (it worked! yay!), but the navigation is still not working as expected, and the Outline mode is nonresponsive: it will not let me move files up and down now. I don't see any reason from it is being nonresponsive, but I don't know what to look for really.

Here is what is happening:
https://hax.lauragibbs.net/sites/story-folder/
Go to the site; we are on the About page, which has null parent, order 0. That is our starting point, right? There is no backward navigation arrow in the upper right-hand corner; just a forward arrow. So that is as expected.

When I click the forward arrow it goes to this page:
https://hax.lauragibbs.net/sites/story-folder/s000093
But it should not do that!
pages/s000093 has as its parent
item-d43de105-2610-4173-910d-a68883eca35c
which is
pages/stories
... so no way would that be the forward-arrow destination from the about page. It should instead go to r0001, because that has null parent and order 1, which means it should be the forward arrow destination.

Then when I click the forward arrow again, pages/s000093 goes to 
pages/s000113
Why does it do that?
pages/s000113 has as its parent item-71896c13-98ee-4c87-a140-b6d1e4b7d24b (page r0001).
So again, there is no rhyme or reason that I can see. But there has also been no rhyme or reason to the order in which new pages are added. Perhaps this is related...?

Anyway, I understand now how the id/title/location work, and how parent and order create the outline... but I don't understand why it's behaving the way it does. At least now that the out-of-whack between the title and location is fixed, I feel confident about adding pages...

But I can't make heads or tails of the navigation.

I will be glad to try any kind of experiment anyone wants to suggest. For now, I will just go back to adding pages and content, assuming that eventually it will be possible to organize the stuff. :-)

**Comment by btopro** [comment]
outline nav is now in the correct order. forward / backward nav sticks as it should
