### ISSUE TITLE
 RSS: domain attribute needs set for URLs in the feed to work

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#323]
The full-feed RSS is working! THANK YOU SO MUCH!
I used this XML address to subscribe to the feed in Inoreader:
https://hax.lauragibbs.net/sites/story-folder/rss.xml

And then I was able to use Inoreader's HTML rendering of the RSS to pop the story content into a blog post here, which is exactly what I wanted to be able to do:
https://olebrerrabbit.blogspot.com/2019/07/latest-hax-story.html
That will pull the content of the HAX site in automatically.
(Maybe someday you all might think about an HTML syndication service; it is super-useful. I'll be glad to document the user-side of the Inoreader HTML service if you want. I've never seen anything else like it, and it's not complicated really; just rendering HTML out of the RSS feed.)

Anyway, here's what I noticed: the title link does not go to the page as expected, and I think that is because there is a relative link in the XML file. For example:
(I don't know how to paste in HTML code here so that it does not render; sorry about that -- anyway, you'll see what I mean if you look at the link tag in the XML file)
<item>
<title>S000120</title>
<link>/s000120</link>
<description>
<![CDATA[

I have never messed around with the actual XML file, but it looks to me like that might be the problem. So, for example, in that blog post, the link address for the title of the item is:
https://hax.lauragibbs.net/s000099

That's not a good address; it would need to be:
https://hax.lauragibbs.net/sites/story-folder/s000099

Especially for people who use RSS in a more traditional way in a feed reader, clicking on the links in the reader to go the content online, this is really important. 

Let me know if there is any other info I need to supply. And THANK YOU again for this full-text RSS. After I finish with Jones's Gullah stories, I'll pick a book to work with that has some images so I can test out the media rendering too. 

Yay RSS!!!!!!!!!!!!

**Comment by lauragibbs** [comment]
Here's screenshot since I can't figure out how to copy-and-paste code in here without it rendering :-)

![Screen Shot 2019-07-16 at 10 23 03 AM](https://user-images.githubusercontent.com/19476543/61302434-c2c22a00-a7b3-11e9-8d99-018d7aceeb08.png)

**Comment by btopro** [comment]
Do you have RSS from something else you've pulled into inno that does it correctly? I want to make sure I've got the right methodology for handling this like others as I've ingested a lot of RSS in the past but never from my own systems (obviously).

Full link paths get tricky too. I don't like hardcoding URLs in things (as the files get generated per save) as it then locks the content to a specific URL (which is what I'm trying to avoid there). However, there might be a way of saying "ok the link's base is "/sites/stories" as a way of keeping the URL out of it but we'll see. You've definitely changed our mindset from "static always" to "Static as simple option" from how we get these out to people / share links around stand point.

Also if you love RSS you might want to look at the "Learn" theme in the settings gear. It's the theme that https://haxtheweb.org/ uses and provides direct links to the RSS / Atom feed as well as integrated search.

**Comment by btopro** [comment]
@lauragibbs Try this -- Hit the settings gear and fill in the domain field and hit save. 
If you make the domain `https://hax.lauragibbs.net/sites/story-folder` I believe it'll work.

Then edit or add a new post and check the RSS feed, it should rebuild the RSS feed with the domain name included in all the links.

**Comment by lauragibbs** [comment]
I should clone my site to have a playground to try the different themes! I will do that when I get back from Austin.

Here is how a Blogger RSS file looks:
https://mytalespinner.blogspot.com/feeds/posts/default

It has full link paths, and I think for RSS that might not be a problem. RSS is a very ephemeral thing, constantly disappearing itself as the RSS XML file gets overwritten with each update. Also because the whole idea of syndication is that you are out there in other web contexts (feed readers primarily, but other syndication options too), so full link paths might make sense even if for other purposes relative is better.

FWIW in addition to the HTML syndication, Inoreader wants to give me a JSON too! I have no idea how JSON works, but it must be useful to somebody, since Inoreader added that as an option a while back. here's their JSON rendering of the RSS XML data:
https://www.inoreader.com/stream/user/1005987531/tag/RSS%20HAX/view/json

These are the export options they give me for any RSS feed or for the RSS recombinations I create using Inoreader (this is why RSS is important to me; Inoreader is my main tool for distributing content):

![Screen Shot 2019-07-16 at 12 58 55 PM](https://user-images.githubusercontent.com/19476543/61313967-839ed380-a7c9-11e9-9e77-745b2810c2f8.png)

**Comment by lauragibbs** [comment]
GOT IT! I haven't done my stories yet for today, so that means I'll be able to test and report back. More later! :-)

**Comment by btopro** [comment]
the domain field is used for publishing but also these files that are auto-generated leverage that item

**Comment by lauragibbs** [comment]
YAY!!!!!! I went to settings and edited the domain field like you said.......
and that WORKED!!!!!!!!!!
Now the title links in the RSS are good!!!!!!
When I finish the current book, I'll pick a book with illustrations to process next so that I can check out how the media management will work.
Yay RSS!!!!

**Comment by btopro** [comment]
excellent. Now we'll just need to document this and what it provides for the system. This might make a good tag for student project (hence will)

**Comment by lauragibbs** [comment]
and now I have my RSS feed set up to share AND the RSS-powered email subscription service that goes with it (god knows why people want more email, but they do, ha ha). And listen, do you all have some HAX logo art? I'm using this dopey manila file folder, but I'd be happy to use a HAX logo. I've seen a nifty logo for ELMS I think... if you have something HAX specific I could start using that!

![Screen Shot 2019-07-16 at 2 15 38 PM](https://user-images.githubusercontent.com/19476543/61319105-83f09c00-a7d4-11e9-9eae-fc562441239e.png)

**Comment by btopro** [comment]
@michael-collins has made some previously (and he made the elmsln ones) and I didn't love it so we currently don't have a dedicated hax one. One thought was to have the elmsln logo as it's an unbrella or we have the "powered by" variants among others:
- https://github.com/elmsln/elmsln-logos/tree/master/png-lowres-transparent
- https://github.com/elmsln/elmsln-logos/tree/master/elmsln-powered-sticker

I'd prefer some kind of Black mirror style https://codepen.io/btopro/pen/YomdQX
or Stranger things http://makeitstranger.com/hax-theweb

;)

**Comment by lauragibbs** [comment]
I bet for sure you will have students in your class who would be up for a logo-design adventure! :-)
