### ISSUE TITLE
PLAIN NON HTML Text paste is not working

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#325]
The new version is refreshing great now, I really appreciate not having to refresh as I add new pages and edit. THANK YOU!

The copying-and-pasting is not working, though. Before, I could paste in text and I lost all the formatting. So, mostly I would edit in the HTML view, but I also did some pasting in of text, like into the header space since that text didn't have line breaks or formatting.

Now, though, I cannot paste into the header space. When I try to paste (using Control-V, Shift-Control-V, and also the Edit-Paste menu item in the browser), literally nothing happens.

Previously, I could paste but all formatting, even line breaks, were stripped.

Now I cannot paste.

I'm working in Chrome; I haven't gone to see if same problem in Firefox.

I can keep on working like this in the HTML view, no problem... but being able to paste, and especially to paste-with-formatting, would save me some clicks.

I like the new light-not-dark HTML view a lot! That's much easier for me to see. :-)

**Comment by btopro** [comment]
@nikkimk can be credit for the light html edit view.

As for the copy paste I'm not sure I can replicate this as I was just able to copy and paste things in there. is there a specific thing you're copying from I could look at to see if there's a specific issue?

**Comment by lauragibbs** [comment]
I cannot even copy and paste WITHIN a HAX page.
Literally nothing happens.
Before, I was able to copy and paste within a HAX page, no problem, and I was also able to copy from plain text (I do my editing in plain text file, so only formatting is line breaks).
I'll go try in Firefox now and report back.

**Comment by btopro** [comment]
lol. make up your mind laura --

Laura last week "I want to keep formatting" (Bryan makes it support formatting.... and breaks non-formatted text)
Laura this week "I want to paste non-formatted text"
;)

I was able to replicate it thank you for that report. If you go into a word doc or another website and copy text it'll paste. But I am able to replicate the issue your describing of pasting non-formatted, plain text.

**Comment by lauragibbs** [comment]
No problem in Firefox: pastes within documents, pastes from text file, no problem. Linebreaks are preserved now!!!
I will just work in Firefox for now.
Is there information I can send you about Chrome that will help troubleshoot? 
Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by lauragibbs** [comment]
ha ha, just saw your other comment:
linebreaks are the only formatting I need preserved...
but other users probably will want other formatting? don't know.
but I need my linebreaks :-)

**Comment by btopro** [comment]
nah that's probably enough (and strange too that FF is good w/ this).
