### ISSUE TITLE
Exploration: Aligning HAXcms and ELMSLN release schedules / branches

### ISSUE THREAD

**Issue by btopro** [elmsln/HAXcms#326]
HAXcms dictates the front end asset build schedule for ELMS:LN as of 0.11.0. We're on version 0.9.0 of HAXcms. HAXcms technically is inside of elmsln's codebase with 0.11.0 but not activated until 0.12.0. We should align these versions to avoid future confusion as to the capabilities of each.

While this would then require there to be code coordination between the two for backend things, it would help further emphasize the nature of the front-end code unification. We could possibly find a way of pegging those versions to the npm publishing of said assets but that might be down the road a bit as versions in our monorepo are somewhat meaningless snapshots in time for others (as everything has stabilized there).

If we did decide to do this, we should bump haxcms up to 0.11.x (skip 10, move all 0.10.x issues to 0.12.x) and then when ELMSLN 0.11.0 releases, publish a 0.11.0 of haxcms to match. @heyMP thoughts on this as you work across both?

**Comment by heyMP** [comment]
I don't immediately see a downside to this.  I would be fine with that.

**Comment by rickhumphries** [comment]
This would make sense for us too so no objections over here

**Comment by btopro** [comment]
Ok. I'll sit on this a bit but when 0.11.0 of elmsln comes out then maybe I'll bump haxcms to 0.11.0 just to attempt to keep them in sync and we'll see how practical it really is. As we get less and less Drupal and more and more headless apps / haxcms elements running as an option in courses then we'll see how reasonable it is

**Comment by btopro** [comment]
this happened starting with 0.11.x
