### ISSUE TITLE
title and location fields out of whack again

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#328]
HELP! I am going to have to stop creating pages until these problems are fixed; it's not safe for me to keep creating content. I had followed my usual procedure today: 4 pages worked fine, but when I got to the last of my 5 pages for today, S000130, which I just created, I went to edit the page, and instead of a blank page, it was displaying content from another page, S000125. Screenshot below of what the details show; it is that mismatch between the title and the location, which I also ran into earlier this week. The last new page I had created yesterday was S000125 which is the page that has gotten tangled up with the last of the new pages, S000130. So, this is not totally random; I hope that will help you figure out what's going wrong.
If there is no reliable way to create new pages along with no reliable way to try to do some basic site organization, I'll need to hold off on adding more content. I was really hoping to get a lot done before leaving for Austin next week, but this is pretty frustrating; if I don't have a way to safely add content and edit it, I'm stuck. I do know how to manually change the title/location, but I'm not going to do again here because this problem should not be occurring. Hopefully you can figure out what is causing it, and presumably the solution to this problem with adding/editing new pages will also lead to a fix for the problems with the outline and site navigation. Let me know if there is more information I can supply!

![Screen Shot 2019-07-17 at 12 00 27 PM](https://user-images.githubusercontent.com/19476543/61391485-ca083700-a88a-11e9-8b2f-39372ee05ff1.png)

**Comment by lauragibbs** [comment]
Relevant URLs

https://hax.lauragibbs.net/sites/story-folder/

https://hax.lauragibbs.net/sites/story-folder/s000130
(apparently not found because it shows the "about" page, although S000130 is there in the sidebar navigation)

https://hax.lauragibbs.net/sites/story-folder/stories/s000125
(which shows S000130 as the title, but the content is the correct)

https://hax.lauragibbs.net/sites/story-folder/stories/s000125-1
(I never created this page, but this is the URL that the sidebar navigation now points to!)

Clearly, serious problems here.

**Comment by btopro** [comment]
please go to https://hax.lauragibbs.net/ select your site and download it, zip it and email it to me, I'll DM you my email address on twitter

**Comment by lauragibbs** [comment]
Got it! Is there a download button somewhere at hax.lauragibbs.net, or should I log on at Reclaim and download from there?

**Comment by btopro** [comment]
click this button and it'll select your site and you should see a menu pop up that says "Download" on it somewhere
![2019-07-17_12-57-23](https://user-images.githubusercontent.com/329735/61395041-7a2d6e00-a892-11e9-8206-94e5a0cb4ed6.png)

**Comment by lauragibbs** [comment]
Got it! Will go do now. THANK YOU!

**Comment by lauragibbs** [comment]
I just notice another huge problem/clue:

I've been assuming that the URLs are stable based on the name I give to the page:
https://hax.lauragibbs.net/sites/story-folder/S000001 and so on up through
https://hax.lauragibbs.net/sites/story-folder/S000130 (the last page I added)

But now I see that the Outline actually changes the URL... total disaster for me, and it's also not happening consistently.

For example, this page is fine:
https://hax.lauragibbs.net/sites/story-folder/s000120
It's under Stories now (in my desperate attempt to clean up the navigation mess), but the URL is still good, as it should be.

But other pages do not have the URL they should:
https://hax.lauragibbs.net/sites/story-folder/s000121
does not work; instead, it is now:
https://hax.lauragibbs.net/sites/story-folder/stories/s000121

So, that means it is a total no-go for me to try to use the Outline view. I need good, stable URLs. If moving things around in the Outline is going to change URLs (and worse, to do so only sometimes?), then I cannot use the Outline to organize the site contents.

I have no idea why there is an inconsistency about the way pages are, or are not, in the "stories" subdirectory. Both 120 and 121 appear to be in the "Stories" section of the Outline (that's how they look in Outline mode and that's what shows in the site sidebar navigation), but one of them has stories in the URL and one does not.
https://hax.lauragibbs.net/sites/story-folder/s000120
https://hax.lauragibbs.net/sites/story-folder/stories/s000121

I guess that discrepancy is what accounts for why the Outline mode is being nonresponsive when I try to move things around there, and presumably that discrepancy is also causing the problems with the page titles and locations getting out of whack.

I'm guessing I may need to just hold off on using HAX until there are some stable site organization tools in place. I've been staging the content in GoogleDocs so I'll just keep creating the GoogleDocs until all the issues have been sorted out here. We can use the existing site as a kind of experiment just to figure out what's going on and if it is fixable, plus if it is really sustainable to create a site with many pages in the current HAX iteration.

**Comment by btopro** [comment]
so a few things here.
- The URL / path when in outline mode defaults to where ever it's placed. So if it's in a sub-folder it'll show up that way in the outline + the website + the url to match (it's an SEO thing). If wanting to change that path, go to the page, then hit the thumb print icon in the bottom and modify the location and hit save fields (this is also how you can rename something if naming is off):
![2019-07-17_14-29-24](https://user-images.githubusercontent.com/329735/61403097-8d483a00-a8a2-11e9-91ac-ff84643e2fb6.png)

Specifically on the 130 pointing the wrong place. In looking at the physical files under the hood it appears that something happened where the outline got confused. If you click on 125 you should see it go to `s000125-1`. So to correct this:
- Go to the page titled 130 yet URL / content is 125 and hit the thumb print
- change the TITLE of this to be 125 and save
- Go to the  url s000125-1 and hit the thumbprint. Rename this 130 and change the location to point to 130 as well

This should clear this issue up. I'm looking into the pagination issue since I was able to replicate it and I see why that's happened

**Comment by btopro** [comment]
#330 is what caused this so the names of things now won't get bounced around. We also have a setting surfaced via UI that can modify this behavior (and it is defaulted to off)

![2019-09-25_21-17-13](https://user-images.githubusercontent.com/329735/65650683-e4bd0180-dfd9-11e9-8546-39ddc0071cca.png)
