### ISSUE TITLE
Uploading files "Unexpected Server Error" 

### ISSUE THREAD

**Issue by Geek-Fish** [elmsln/HAXcms#337]
Throwing an error when I try and upload an image. Here's the console log:

[Error] SyntaxError: JSON Parse error: Unrecognized token '<'
	parse (hax-upload-field.js:147:6177)
	_fileUploadResponse (hax-upload-field.js:147:6177)
	_fileUploadResponse
	dispatchEvent
	onreadystatechange (vaadin-upload.js:43:7371)

and then

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (saveFile.php, line 0)

MAMP running PHP 7.3 (on an iMac Pro)
Browser: Safari 12.1.2 and Chrome 75.0.3770.142

**Comment by btopro** [comment]
can you check inside of the `sites/{SITENAME}/files` and see if it did actually upload there just reported a failure? Good chance this is related to the error reporting issue that I squashed recently

**Comment by Geek-Fish** [comment]
Yes, all of the uploads are in that folder.

**Comment by btopro** [comment]
ok, so this is most likely that prev issue. can you pull a copy of master and overwrite your system directory and see if this error goes away?

**Comment by Geek-Fish** [comment]
Pulled and replaced system folder. Error still present.

**Comment by Geek-Fish** [comment]
Interestingly enough, this is the ONLY file that I try to upload that doesn't throw the error. 
![Dance](https://user-images.githubusercontent.com/8617164/62082158-36d3e780-b222-11e9-90f8-fa12ef94d50c.gif)

**Comment by btopro** [comment]
... hmm... so other image files DO? are they a certain size or something?

If you go into inspect and do Network then XHR THEN upload you should be able to see what the error message is that it's dying on.

**Comment by Geek-Fish** [comment]
Yes.

I tried changing file names, sizes, types... For some odd reason this one
does not error out.

I'll do that when I get home and report back.

**Comment by btopro** [comment]
probably bc it's hilarious looking

**Comment by Geek-Fish** [comment]
That's how excited we get when it only takes us 10 takes to get a line out.

**Comment by Geek-Fish** [comment]
XHR results of a 'failed' file (but it is in the files folder):

{"status":200,"data":{"file":{"path":"\/Applications\/MAMP\/htdocs\/HAXcms\/sites\/test\/files\/\/fil111e.jpg","fullUrl":"\/HAXcms\/sites\/test\/files\/fil111e.jpg","url":"files\/fil111e.jpg","type":"image\/jpeg","name":"fil111e.jpg","size":315181}}}<pre>Array
(
    [type] => 1
    [message] => Uncaught Exception: "/Applications/MAMP/htdocs/HAXcms/_sites/test" is not a git repository in /Applications/MAMP/htdocs/HAXcms/system/lib/Git.php:282
Stack trace:
#0 /Applications/MAMP/htdocs/HAXcms/system/lib/Git.php(237): GitRepo->set_repo_path('/Applications/M...', false, true)
#1 /Applications/MAMP/htdocs/HAXcms/system/lib/Git.php(103): GitRepo->__construct('/Applications/M...')
#2 /Applications/MAMP/htdocs/HAXcms/system/lib/HAXCMSSite.php(143): Git::open('/Applications/M...')
#3 /Applications/MAMP/htdocs/HAXcms/system/saveFile.php(15): HAXCMSSite->gitCommit('File added: fil...')
#4 {main}
  thrown
    [file] => /Applications/MAMP/htdocs/HAXcms/system/lib/Git.php
    [line] => 282
)
</pre>

**Comment by btopro** [comment]
well there's your answer. I bet you don't have Git on your computer if ur running this in mamp
is that accurate?

**Comment by Geek-Fish** [comment]
I have git version 2.20.1 installed based on terminal

**Comment by btopro** [comment]
did you start out making this site in XAMP which failed before and then switch to MAMP?

Something happened where it didn't do git init (something we can trap for but checking for what caused it)

**Comment by Geek-Fish** [comment]
I left the XAMPP install go and started fresh on MAMP. Here's what I did on MAMP:

- Installed MAMP
- Cloned repo with GitKracken into htdocs in MAMP (https://github.com/elmsln/HAXcms.git)
- Logged into the site editor with the username/pass provided on screen when visiting the new site install
- Created a new website (needed to manually refresh for it to show up in the list though... Not sure if that is a bug)
- Tried to upload a photo
- Death to all uploads.

**Comment by btopro** [comment]
yeah so it sounds like it didnt make a git repo hence calls bricking. Try making a new site and do the same XHR inspect to see what it's bricking on, it's definitely a git issue. Working on something to help try and account for this at least a little bit

**Comment by Geek-Fish** [comment]
I'll see if I can track down where this choked, but I fixed it by navigating to the site folder and running 'git init'. We're in business for now, but I'll replicate my install sets to see if I can track down why this happened. 
![Screen Shot 2019-07-30 at 3 39 03 PM](https://user-images.githubusercontent.com/8617164/62159670-444fa700-b2e0-11e9-9f1b-7a7d614a746e.png)

**Comment by btopro** [comment]
yea please do. doing a commit now that's going to try and force git init instead of just bricking (tho it still might brick if git isn't there for access)

**Comment by btopro** [comment]
did you do install by navigating the the index.php and it installed via that page or did you run the bash script after getting it downloaded into mamp?

**Comment by Geek-Fish** [comment]
This one I did the install by going to index.php. I'll try the bash script next (did that with XAMPP, but we all know what happened on there).
