### ISSUE TITLE
HTML/ASCII Code in Site Titles

### ISSUE THREAD

**Issue by Geek-Fish** [elmsln/HAXcms#338]
Special characters are displayed as their HTML/ASCII codes. Example: Apostrophe = &#39;
![Screen Shot 2019-07-29 at 4 14 08 PM](https://user-images.githubusercontent.com/8617164/62079323-77c8fd80-b21c-11e9-8d75-ccaffa89fa6f.png)

**Comment by btopro** [comment]
Think we should probably wipe these or maybe even input validate on the client side / notify. These chars could be tricky to support across OSs / browsers given that really your picking the URL for the new site to have it's folder copy and pasted to.

**Comment by btopro** [comment]
@Geek-Fish what did you have as anticipated behavior in putting in garbage input the way @nikkimk would just to upset the apple cart? ;p

**Comment by Geek-Fish** [comment]
@btopro I'm just trying to think like a user ;)

**Comment by btopro** [comment]
that's what she claimed.. ugh, you're everywhere ;)

Here's where htat's being set -- https://github.com/elmsln/HAXcms/blob/master/system/createNewSite.php#L15-L30

You can see we have a unique name / title cleaning function else where though so perhaps we just need to normalize these, or maybe we need a special class function for generating valid machine names and apply it to the site name when it's initially created

https://github.com/elmsln/HAXcms/blob/master/system/createNode.php#L18-L26

**Comment by btopro** [comment]
clean title in core (which is a big class) https://github.com/elmsln/HAXcms/blob/master/system/lib/HAXCMS.php#L608-L630

Maybe we need an additional check for machine name compatibility.

https://github.com/elmsln/HAXcms/blob/master/system/lib/HAXCMS.php#L530-L552

The loader function generates the new site on the fly if its been asked to (which is how the create site can just call load even tho it doesn't exist)
