### ISSUE TITLE
Formalized UI / UX Audit

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/HAXcms#348]
The UI needs a lot of love... It is almost like a developer *ahem* built it without any feedback from the end user aside from the initial input. User testing should be done so that product devs/owners can see if their product is fitting users' needs.

**Comment by onelittlebecca** [comment]
**** vital for any kind of wide adoption as UI is not intuitive and somewhat clunky to maneuver through

**Comment by btopro** [comment]
#106

**Comment by btopro** [comment]
tagging related issue which has some mock ups @michael-collins has worked on. We've got several other documents internally that I am not at liberty to share as to the direction the UI will be heading.

It's also had quite a bit of user input and feedback as well as the mental model explained in UX concepts -- https://haxtheweb.org/ux-concepts but your assessment is right that we need a more formalized UX audit then early adopters and Mike's moon shot ui.

**Comment by michael-collins** [comment]
The latest  discussion about UI should be on #247 , #106 is an older post. Feel free to jump in if you have specific ideas!

**Comment by btopro** [comment]
closing as round 1 took place at NARA and this is now on-going, splitting off into it's own issues https://github.com/elmsln/issues/issues?q=is%3Aissue+is%3Aopen+label%3A%22UX+Study+1%22
