### ISSUE TITLE
Add cache busting to publishing step

### ISSUE THREAD

**Issue by heyMP** [elmsln/HAXcms#368]
Changes to site.json, css, js, and similar assets aren't immediately changed for users.  We could have a some time of build steps that either updates the e-tag of index.html or adds cache busting strings to file imports to ensure the changes are immediately reflected to the end users.

**Comment by btopro** [comment]
Maybe we can peg this to the pwa. Instead of the service worker sending a message about new content hey reload, it could just set a timestamp variable which would force a fresh copy of files. This is how it works when NOT published so we already have all the logic in there for it

**Comment by btopro** [comment]
#428 is exposed under SEO and now that we've got .php driven pages and they can be upgraded dynamically based on saving the manifest we can support this in what currently exists and without the need for the publishing side of things. You can now disable the service worker if it's a site where you need instant updating / none of the advanced offline capabilities we've got available.

The CDN can now also be cached for offline viewing though it's not the default
