### ISSUE TITLE
MAMP access denied error

### ISSUE THREAD

**Issue by tomsshow** [elmsln/HAXcms#389]
I get a 'Login is required' message when I visit localhost/system/login
however, when I look at the xhr login request, I see an 'access denied' message

**Comment by btopro** [comment]
I'm not able to replicate this, could you get the latest copy soemtime and shoot a video showing how you generate this issue. I just pulled down the latest and it worked fine.

**Comment by btopro** [comment]
![2019-09-13_08-09-58](https://user-images.githubusercontent.com/329735/64861420-e3fd9600-d5fd-11e9-91ca-8ea8e92777e4.png)

**Comment by tomsshow** [comment]
https://youtu.be/Ueg3nBIVGcQ

The video is currently processing, as im typing this. Give it a sec if it doesn't load up.

**Comment by btopro** [comment]
hmm.. I wonder if MAMP on PC needs to be told to allow htaccess overrides OR, if the invisible files aren't being copied over when your unzipping a folder for the first 10 minutes of the video ;)

There should be a `.htaccess` file that tells MAMP's internal apache / php engine to reidrect `/login` to `/login.php`.

See if you can google anything around this issue space like getting htaccess files to work in mamp or things of that nature. I'm not experiencing this issue when I follow the same steps. -- https://github.com/elmsln/HAXcms/blob/master/.htaccess is the file for reference if one does not exist create one w/ those contents (but my guess is that it's not loading it as opposed to it not existing)

**Comment by btopro** [comment]
try this again on a new copy but I can't replicate this and the install has been cleaned up in 0.12.x

closing for now
