### ISSUE TITLE
Gradebook microservice

### ISSUE THREAD

**Issue by btopro** [elmsln/HAXcms#395]
- Excel sheet
- Wired to Box / some storage location
- Slim php layer that accepts university login, only shows them their record in the "backend"

There's almost nothing to it beyond converting to CSV to more easily parse the "database" (aka excel file). Web components could at least help with the visualization side on the front end and maybe the upload / reupload of the file if we wanted to handle it that way (without a Box-esk storage solution).

Backend, students hit a login system and verify that they are abc123 type login and that is then matched to the 1st row in the "database" (aka csv file). This then ensures they only get piped the JSON data associated with them.

This doesn't really belong in this queue... but I wonder if @heyMP would have ideas of how we could rapidly do this via the docker swarm stuff he's hiding :)

**Comment by michael-collins** [comment]
Why stop at grading? I can configure my entire course with an excel spreadsheet. Fields to include: https://dmd.psu.edu/courses/dmd100-calendar-su18.json

**Comment by btopro** [comment]
hmm... interesting use-case. This could be something easy to pick up and do from the grade book piece. Your use case also would probably fit into HAXcms + schema + node fields and provide a real use-case for doing so (in the case of its tied to nodes of content).

**Comment by btopro** [comment]
older issue; more current stuff in issue queue around active work on the grading tool
