### ISSUE TITLE
Can't change banner image

### ISSUE THREAD

**Issue by juststormy** [elmsln/HAXcms#399]
Trying to change the banner image on simple blog https://iam.hax.psu.edu/mjs100/sites/mjs100/. Getting a forbidden error.
![Capture](https://user-images.githubusercontent.com/1186260/64877993-83cc1b80-d620-11e9-8bad-5895512148d7.PNG)

**Comment by btopro** [comment]
@juststormy can you upload the banner here so I can play with it. I was able to upload a new banner so want to rule out some things

**Comment by btopro** [comment]
oo, messed around a bit and just got this to happen.

**Comment by btopro** [comment]
I see why this is happening and the next version it's fixed which @heyMP and I need to review some more before pushing out to hax.psu
