### ISSUE TITLE
apostrophe issue in description

### ISSUE THREAD

**Issue by juststormy** [elmsln/HAXcms#400]
Trying to add a quote in my description and the apostrophe keeps changing to the code version.
![Capture2](https://user-images.githubusercontent.com/1186260/64878177-eae9d000-d620-11e9-92ae-7e1e2522bc6c.PNG)
![Capture3](https://user-images.githubusercontent.com/1186260/64878220-0654db00-d621-11e9-9ca0-78db3cdbae3f.PNG)

**Comment by btopro** [comment]
fixed this, next release when we push it out will have this included. Thank you for contributing to the future!
