### ISSUE TITLE
Not working in Microsoft Edge

### ISSUE THREAD

**Issue by juststormy** [elmsln/HAXcms#405]
Was trying to see if I could get around the 404 by using Edge. None of the tools appear in the top bar. See screenshot.
![Capture](https://user-images.githubusercontent.com/1186260/64895379-6a3fc980-d64a-11e9-8ee5-bb1397411ad1.PNG)

**Comment by btopro** [comment]
Edge won't be formally supported until the next version is release (of Edge that is). Current Edge we can only do so much to make it mostly work (on the building side of HAXcms that is, viewing side it works though is watered down).  Microsoft is releasing a new version before the end of the year that reaches full compatibility on both viewing and creating side of haxcms
