### ISSUE TITLE
php5-fpm conflict on vagrant install

### ISSUE THREAD

**Issue by ymdahi** [elmsln/HAXcms#423]
Installing via vagrant produces the following error:

@ /var/log/nginx/error.log:
`511#0: *1 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '?' in /var/www/html/system/lib/HAXCMS.php on line 436" while reading response header from upstream, client: 10.0.2.2, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:5454"`

following this error to /var/log/php7-fpm.log:
```
ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address already in use (98)
[29-Sep-2019 03:50:13] ERROR: FPM initialization failed
[29-Sep-2019 04:14:12] NOTICE: configuration file /usr/local/php7/etc/php-fpm.conf test is successful
```

Through some digging found the php5-fpm also running on server, so `sudo service php5-fpm stop` was enough to get past error.

**Comment by btopro** [comment]
ahh I have an old vagrant image that this is pointing to. Trying w/ Ubuntu 18 as we have a script to help get dependencies there.

**Comment by btopro** [comment]
better image is in place, will install now but has an issue with apache and rewriting paths for some reason... still looking

**Comment by btopro** [comment]
ok I think I got it fixed (also, holy cow is Vagrant fast with HAXcms!)
