### ISSUE TITLE
The case of the mysteriously disappearing list...

### ISSUE THREAD

**Issue by beb5040** [elmsln/HAXcms#456]
![Screen Shot 2019-10-28 at 4 57 37 PM (3)](https://user-images.githubusercontent.com/45569686/67717963-25c37f80-f9a5-11e9-8671-d4c425ce2d1c.png)

When using grids, or layouts it will not accept a bulleted list (assembled naturally)

However, you can insert one with ctrl+V. You can do this with a pre-existing list already built in HAX or with one generated from a Word doc. If you take from Word, however, you'll carry over additional formatting and so is ill-adivsed. 

The list is only hidden. It can still be found in the legacy rich text editor and in the HTML as seen above marked with "slot" tags.

**Comment by btopro** [comment]
next release will solve this. Has to do with the "slot" issue mentioned which a lot of "dont let things get lost" logic has been applied :)
