### ISSUE TITLE
Support relative links within a CMS (Drupal specific)

### ISSUE THREAD

**Issue by onelittlebecca** [elmsln/HAXcms#488]
Create internal links to other pages on website (using relative links)

Related issue: https://github.com/elmsln/HAXcms/issues/262

**Comment by michael-collins** [comment]
I want to second this feature request.

**Comment by onelittlebecca** [comment]
YAY! SOMEONE LOVES ME! Or at least marginally likes one thing I have said.... <coughcough BRYAN coughcough>

**Comment by nikkimk** [comment]
So... some of the initial ground work exists as anchor-behavior. We need to think about the interface for hooking this up, but the actual anchor would work with the `anchor-behaviors` component on a page.

**Comment by onelittlebecca** [comment]
I don't know what you are referring to when you say anchor-behaviors component... and with drupal, would need to integrate, (I imagine) using tokens

**Comment by btopro** [comment]
anchor behaviors is the visual piece that would be providing like the in context results. Wouldn't need tokens, could have like an autocomplete / searchable thing that's hitting a Drupal end point or HAXcms or WordPress to supply the list of links. HAX then is still agnostic and if that end point exists (searching for content to reference) then it would enable it. similar to how IMCE / CKEditor has the ability to search Drupal for nodes to link to if you have the right module enabled (but without that and automatic)
