### ISSUE TITLE
Page Fonts Inconsistency

### ISSUE THREAD

**Issue by McGarvelcuddy** [elmsln/HAXcms#492]
The menu font for my first few pages looks like it is in TNR and my most recent page seems to be in another font in the menu.  
The site in question is http://mcgarvelcuddy.com/haxcms_1/sites/soap-site-accessibility-evaluation/accessible-design-re-imagination
![HAX page list font](https://user-images.githubusercontent.com/54725578/69110667-6add4d80-0a49-11ea-836e-241b79060455.png)

**Comment by btopro** [comment]
I believe the next version fixes this as that asset has been refactored under the hood to have styles applied more consistency and the element load faster.
