### ISSUE TITLE
CSV Table not showing first row

### ISSUE THREAD

**Issue by lizhewen** [elmsln/HAXcms#505]
When I'm trying to create a csv table from file, the first row is not showing properly and I had to manually add a placeholder as first row to get the column headings show up.
![image](https://user-images.githubusercontent.com/32529051/71024567-2f2eb580-20d3-11ea-8220-1515d291384d.png)
![image](https://user-images.githubusercontent.com/32529051/71024572-348c0000-20d3-11ea-9307-95f363c9506f.png)

**Comment by btopro** [comment]
@lizhewen can you upload the file here or paste it exactly as formed?

**Comment by btopro** [comment]
I'm able to replicate part of this. ugh.

**Comment by lizhewen** [comment]
Yeah my work-around is to add that placeholder. But you definitely should know this. I created the file using excel, not sure if that has anything to do with this.

**Comment by btopro** [comment]
found it, this was an easy oversight, pushing up new version shortly. thank you for the report

**Comment by btopro** [comment]
@lizhewen this is now fixed out there might need to super refresh or something but it'll print the 1st row. an oversight in mass converting elements to a faster format thanks for the report
