### ISSUE TITLE
HTML formatter adding extra space between some elements

### ISSUE THREAD

**Issue by heyMP** [elmsln/HAXcms#514]
An instructor is running into an issue where she is adding subscripts using the `<sub>`,`<sup>`,`<em>` tags.  She adds a period immediately following one of those tags and an extra space is seen on the screen.  

Here is an example of the html that is saved:
```
<p>
  You would be ripped apart exactly at the Schwarzschild radius when the mass of
  a black hole is about <span>2,000 M<sub>sun</sub></span>
  .  For lower mass black holes
  <em>r<sub>rip </sub> > r<sub>sch</sub> </em>
  and one is torn before reaching the event horizon. If you want to see what it
  than 2,000 M<sub>sun</sub>
  . However, this delays your tidal disruption by only a small amount.
</p>

```

I think this is related to #305

**Comment by btopro** [comment]
is this the latest hax that's on hax.psu?

**Comment by heyMP** [comment]
Yeah it is.

**Comment by btopro** [comment]
we'll need to see the actual steps to reproduce this as I haven't been able to in many months though I don't doubt it being possible. HAXcms repo is a bit ahead of when we had things in.

**Comment by btopro** [comment]
I wonder if it's because these register as valid HTML tags / children in a "slot" and therefor go through a different type of processing. it's not all tags that will cause this effect.

**Comment by btopro** [comment]
(I just witnessed this with strong tag)
