### ISSUE TITLE
Vertical spacing for nested lists should be the same as list items.

### ISSUE THREAD

**Issue by nikkimk** [elmsln/HAXcms#525]
base styles for lists and list items need to take nested lists into account so that list items with nested lists don't have extra space.

<img width="850" alt="Screen Shot 2020-01-06 at 10 07 17 AM" src="https://user-images.githubusercontent.com/5090492/71827132-905ffe00-306d-11ea-8618-114053525ac6.png">

**Comment by btopro** [comment]
fixed in NARA thread work
