### ISSUE TITLE
published pages not working

### ISSUE THREAD

**Issue by heyMP** [elmsln/HAXcms#540]
The published pages setting is no under `metadata.core`.  That needs to be reflected in haxcms-site-store.js

**Comment by btopro** [comment]
.core? when was it under there?

**Comment by btopro** [comment]
Just verified now on hax.psu on one of my sites. Maybe we changed the name of the setting at one point but this can be done via the UI now
![2020-01-12_11-12-31](https://user-images.githubusercontent.com/329735/72221864-88500480-352c-11ea-97d8-b94c5558dff4.png)

![2020-01-12_11-13-06](https://user-images.githubusercontent.com/329735/72221865-8a19c800-352c-11ea-937a-fd624cebdae7.png)
