### ISSUE TITLE
Error: Cannot find module 'rollup-plugin-terser'

### ISSUE THREAD

**Issue by cgldevel** [elmsln/HAXcms#553]
On initial install, I ran into the following error running yarn install/start: 

Error: Cannot find module 'rollup-plugin-terser'

Possible fix... Add lastest version of rollup-plugin-terser to package.json and rerun yarn install / yarn start.

**Comment by btopro** [comment]
what directory are you in when this happens?

**Comment by cgldevel** [comment]
On the new directory (haxcms).

**Comment by btopro** [comment]
@heyMP did you remove that when working on enhancing the tooling?

**Comment by heyMP** [comment]
no, it's been missing I think.

**Comment by btopro** [comment]
oh ok. I'll add it to future boilerplates
