### ISSUE TITLE
Review files in build directory that are potentially unused

### ISSUE THREAD

**Issue by petecarapetyan** [elmsln/HAXcms#559]

**Comment by btopro** [comment]
To hit maximal browser compatibility while still adhering to principles of unbundling there are 3 compiled editions of assets in folders called ES6 (which is effectively ES8 bc its pegged to evergreens), ES6-amd which works on versions of Firefox/Safari/Edge prior to web component adoption, and hten ES5 which works on IE11 / older non-es6 browsers. This leads to triple the build  directory so build directory is closer to 9 megs in reality, which isn't all served over the wire.

We could reduce the size of this but I'm not sure the point as PDF.js (600kb) is required if using an inline pdf rendering element but not if you don't have one on the page. Also there are CDNs for production implementations.
