### ISSUE TITLE
3 word site Lighthouse performance of 33 

### ISSUE THREAD

**Issue by petecarapetyan** [elmsln/HAXcms#560]
I came to the CMS because it advertised a PWA as output.

Not only is it not a PWA but a score of 33 on a static site with only 3 words is scary bad. Lighthouse says it is most definitely not a PWA.

I'm not so sure about fixing it, but you definitely need to fix the advertising because i would never have come here and wasted time setting it up if I had known this was going to be the result.

Great ideas, but if you bring people in with different expectations you're not helping your street cred. My 2c

**Comment by btopro** [comment]
The (no CDN) local published copy will generate these scores. Perhaps the setting for PWA needs the box checked. Website's being rebuilt. This seems less an offer to help improve the scores and there's a setting to leverage the service worker locally so it should be fine. Thanks for trying it out
