### ISSUE TITLE
haxtheweb.org sidebar obscured by toolbar

### ISSUE THREAD

**Issue by CheckeredFlag** [elmsln/HAXcms#567]
Wanting to get started with HAX so I went to haxtheweb.org, but it doesn't load properly.  The toolbar obscures the left portion of sidebar menu making it unable to be viewed properly.  Same issue on Chrome and Safari on MacOS 10.15.4.

Apologies if I've not posted to the right place - just getting started.

**Comment by btopro** [comment]
Thanks for the report. I might just disable hax on that site bc it's got a very specific hack to our code base to support a static site faking that it's got an editor :) and we have a good demo that resets itself every day here -- http://haxcms.do1.demos.elmsln.org/ (admin / admin)

**Comment by btopro** [comment]
fixed
