### ISSUE TITLE
suPHP Permissions Issues

### ISSUE THREAD

**Issue by timmmmyboy** [elmsln/HAXcms#568]
This may be Reclaim Hosting specific, but likely useful to know for many shared hosts out there. suPHP is a pretty popular handler for PHP and has pretty specific permissions where things like setting folders to 777 is a no go. The default that "just works" is 644 for files and 755 for permissions. Permissions that are too permissive throw an Apache internal server error. 

I've worked around this a bit by having our install script reset some of the more permissive files and folders that install.php sets back to these defaults and things still work just fine. But as of 1.0 the upgrade is not working at all, with the site just hanging attempting to load and internal server errors pointing to the /build and /assets folders.

![Screen Shot 2020-04-02 at 10 02 31 AM](https://user-images.githubusercontent.com/3890972/78260812-654e4480-74cc-11ea-851a-1a2224d6eab3.png)

```
[Thu Apr 02 14:05:03.573849 2020] [core:crit] [pid 2841736:tid 47557619128064] (13)Permission denied: [client 173.71.210.254:53623] AH00529: /home/haxcms/public_html/build/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/haxcms/public_html/build/' is executable, referer: https://haxcms.reclaimhosting.com/

[Thu Apr 02 14:05:03.602131 2020] [core:crit] [pid 2841736:tid 47557596014336] (13)Permission denied: [client 173.71.210.254:53623] AH00529: /home/haxcms/public_html/assets/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/haxcms/public_html/assets/' is executable, referer: https://haxcms.reclaimhosting.com/
```

Odd errors since .htaccess doesn't exist in those folders as best I can tell. Maybe it's trickling down from the next level up? But I don't see any breaking changes committed to .htaccess so perhaps it has more to do with the permissions on those folders or what actions are trying to run in them. Mostly thinking out loud here but happy to troubleshoot and if anything is specific to our environment as best I can happy to just build in fixes into our script installer/updater. Running a script we use often to fix permissions https://github.com/PeachFlame/cPanel-fixperms does fix the issue but sort of brute force fix to set permissions across all files and folders for an install.

**Comment by btopro** [comment]
so with running that script you ARE able to get it working? the perms are mostly just laziness on my part. HAXcms to create a new site copies a directory from `system/boilerplate/site` and then rewrites several files and renames everything `sites/whatever`. As long as your still able to do everything as before let me know what perms I should be rewriting things to and I'm happy to test the change and ensure it works everywhere else w/ those settings.

chmod is all one big block in our installer -- https://github.com/elmsln/HAXcms/blob/master/scripts/haxtheweb.sh#L80-L89

**Comment by timmmmyboy** [comment]
I managed to get the permissions stuff fixed up (I'm basically just doing a find and chmod on files and folders during installs and upgrades since it was whack-a-mole trying to do it on a per folder basis). The only other issue I'm seeing right now is POST requests to /system/api are failing, wondering what might cause the rewriterules to throw errors there (403 error)

![Screen Shot 2020-04-03 at 11 24 38 AM](https://user-images.githubusercontent.com/3890972/78377744-00631f00-759e-11ea-9564-f3e01ffc61d1.png)

Apache log isn't giving me anything on that one. Any idea how I might debug that?

**Comment by btopro** [comment]
hmmm... https://haxcms.reclaimhosting.com/system/api/openapi/json should respond with SOMETHING. example: http://haxcms.do1.demos.elmsln.org/system/api/openapi/json

**Comment by btopro** [comment]
DM me the username/pass generated and I can look at what the response is to help on the specific 403 at login to see if that generates any clues. There's a bunch of php rewrites going on in that space

**Comment by btopro** [comment]
hmmm `Invalid token` is bizzare bc those paths dont actually use the token. Is there anything around symlink loading or needing to be told specific paths to load .htaccess files from?

https://github.com/elmsln/HAXcms/blob/master/system/api.php is what's getting loaded but it's rewritten via htaccess and then loads files in this directory https://github.com/elmsln/HAXcms/tree/master/system/backend/php

Biggest switch in 1.x is that there's support going forward for multiple backends; PHP being the current active one but this way we can support nodejs or others going forward

**Comment by timmmmyboy** [comment]
Deleting the system folder so it's completely replaced on an upgrade fixed that. Only other issue I see (which maybe needs a separate issue thread) is a white screen on new site creations under 1.1.1. Previous sites still load but new site creation (both new install and upgrade) shows page like this https://haxcms.reclaimhosting.com/sites/new-site/. No console errors, Apache errors, or PHP errors that I can find to debug that.

**Comment by timmmmyboy** [comment]
Scratch that, PHP error log was in the specific site's folder:

`[03-Apr-2020 19:43:02 UTC] PHP Fatal error:  Uncaught Exception: "/home/haxcms/public_html" is not a git repository in /home/haxcms/public_html/system/backend/php/lib/Git.php:282
Stack trace:
#0 /home/haxcms/public_html/system/backend/php/lib/Git.php(237): GitRepo->set_repo_path('/home/haxcms/pu...', false, true)
#1 /home/haxcms/public_html/system/backend/php/lib/Git.php(103): GitRepo->__construct('/home/haxcms/pu...', false)
#2 /home/haxcms/public_html/system/backend/php/lib/HAXCMS.php(1392): Git::open('/home/haxcms/pu...', false)
#3 /home/haxcms/public_html/_sites/new-site/index.php(48): HAXCMS->cacheBusterHash()
#4 {main}
  thrown in /home/haxcms/public_html/system/backend/php/lib/Git.php on line 282`

**Comment by btopro** [comment]
ha, so if there's no git library on the server it's mad. ok I'll have to trap for that

**Comment by btopro** [comment]
or I guess it's that the system isn't in version control. hmm...

**Comment by timmmmyboy** [comment]
Yeah we have git installed on the server but anything installed would not be associated with the repo since we pull from release files.

**Comment by btopro** [comment]
but you dont clone w/ .git to the haxcms root... which is used to generate the hash! FIGURED IT OUT! :) I'll push up a new release soon that has this fix in it and let you know when to try again

**Comment by btopro** [comment]
1.1.2 should have this fixed

**Comment by timmmmyboy** [comment]
Indeed it does! 1.1.2 getting rolled out now to all servers.
