### ISSUE TITLE
basic setup

### ISSUE THREAD

**Issue by tufail7760** [elmsln/HAXcms#574]
I am new here, want to know how to run code first time. So I can start development.

**Comment by btopro** [comment]
Welcome! If you mean HAXcms there's documentation here -- https://haxtheweb.org/documentation-1/haxcms/installation

ddev (https://www.ddev.com/) is what we recommend to get working locally on building new sites. For more advanced site creation methods we have hax11ty (https://github.com/elmsln/hax11ty) if your looking to go the purely static route. 

Any questions feel free to join us at https://bit.ly/haxslack
