### ISSUE TITLE
AMP components in Haxcms 

### ISSUE THREAD

**Issue by 99bits** [elmsln/HAXcms#575]
"AMP went all on web components w/ their marketing and have a ridiculous number of elements that you implement via a direct reference on their CDN https://amp.dev/documentation/components/."

Can AMP components can be used in Haxcms.  For example, the amp-accordion, what would it take to add that as an element in the hax content.

**Comment by btopro** [comment]
any amp element can be used in a theme, I personally won't be using the amp collection at this time but it is a large ecosystem of its own stuff. We have https://webcomponents.psu.edu/styleguide/?path=/story/navigation-collapse--a-11-y-collapse-group-story which might be comparable. Do you mean use in HAXcms like a page of content / theme? Or like place on the page via the HAX editor?
