### ISSUE TITLE
Failing to load my-custom-elements.js

### ISSUE THREAD

**Issue by heyMP** [elmsln/haxcms#93]
When loading the HAXcms site manager page in ddev there is a file type error when loading the my-custom-elements.js file.

<img width="1440" alt="screen shot 2019-02-12 at 8 19 54 am" src="https://user-images.githubusercontent.com/3428964/52645257-6a0dfe80-2eae-11e9-9144-f14c94452cf0.png">

**Comment by btopro** [comment]
pull latest. `ddev stop` `ddev start`

this was an issue with nginx config

**Comment by heyMP** [comment]
I'm still getting that error.

**Comment by btopro** [comment]
pull on your 2800 baud modem and try again. git ignore needed fixed to include that file automatically
